version: "3"
services:
  db:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data2:/var/lib/mysql
    ports:
      - 3306:3306
    platform: linux/x86_64/v8
  rails:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/myapp
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp

    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      DB_HOST: db
      DB_USER: root
      MYSQL_PASSWORD: admin
    ports:
      - "3000:3000"
    stdin_open: true
    tty:
      true
    depends_on:
      - db
  web:
    build:
      context: nginx_docker
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - 80:80
    depends_on:
      - rails  

volumes:
  public-data:
  mysql-data2:
  tmp-data:
