version: "3"
services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/myapp
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp

    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      DB_HOST: db
      DB_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3000:3000"
    stdin_open: true
    tty:
      true
  web:
    build:
      context: nginx_docker
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - 80:80
    depends_on:
      - rails  

volumes:
  public-data:
  mysql-data:
  tmp-data:
